name: Build Blaze

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
           ~/.cargo/registry
           ~/.cargo/git
           target
          key: ${{ runner.os }}-rust-${{ hashFiles('src/**')}}-${{ hashFiles('**/Cargo.lock') }}

      # sorry ossac, this is screwing things when deploying

      - name: Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Build and run Blaze
        run: |
          cargo run --release

      - name: Move output
        run: |
          find /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/ \( -name 'output' -o -name '.git' \) -prune -o -exec rm -r -- {} +
          mv /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/output/* . && rmdir /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/output
          touch '.nojekyll'
          
      - name: Custom Domain
        run: |
          touch 'CNAME'
          echo "blaze.toomwn.xyz" > 'CNAME'
          
          # replace "blaze.toomwn.xyz" with your custom name
          # delete this part of the workflow if you don't have a custom domain
      - name: Pagefind
        run: |
          npx pagefind --site .

      - name: Update master
        run: |
          git checkout -b master
          git add .
          git commit -m "Working branch update"
          git push origin master --force
