name: Cargo Run and Output to Branch

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
           ~/.cargo/registry
           ~/.cargo/git
           target
          key: ${{ runner.os }}-rust-${{ hashFiles('src/**')}}-${{ hashFiles('**/Cargo.lock') }}

      # sorry ossac, this is screwing things when deploying

      - name: Build and run Blaze
        run: |
          cargo run --release

      - name: Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout working

      - name: Clear output branch
        run: |
          git rm -rf .
          mkdir temp
          git add -A
          git commit -m "Clear branch"
          git push origin working --force

      - name: Move output
        run: |
          mv /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/output/* .
          touch '.nojekyll'
          
          
      - name: Custom Domain
        run: |
          touch 'CNAME'
          echo "blaze.toomwn.xyz" > 'CNAME'
          

          # replace "blaze.toomwn.xyz" with your custom name
          # delete this part of the workflow if you don't have a custom domain

      - name: Update Working
        run: |
          
          git add -A
          git commit -m "Working branch update"
          git push origin working
